---
gems: [jekyll-paginate]
# collections:
#   portfolio_items:
#     output: true
#     permalink: /portfolio/:title

excerpt_separator: "<!--more-->"
exclude: ['sass/']

paginate: 5
paginate_path: "blog/page:num"

permalink: /blog/:title
---
